### PR TITLE
Create example-data.egp

### LINKED ISSUE #4: I think you *can* store SAS EPG projects in a Git Repo...
I had originally attempted to get this to work, but must have been doing something wrong. I think I've got the process down correctly now.

**Summary:**

We use SAS EPG fairly extensively as our editor and workspace manager when it comes to SAS. Our problem at-hand: how do we combine the use of Git with our use of SAS EPG?

I had read [here](https://github.com/cjdinger/source_control_with_saseg) that it's possible to have a portable SAS EPG file stored inside a Git Repo. This would be great for collaboration, allowing us to use the diagram/network view in organizing source files, while also leveraging the use of version control.

**Process:**

Steps must be completed in order:

1. Create a brand-new SAS Enterprise Guide Project.
2. Inside the project, Properties > File References: check "Use paths relative to the project for programs and importable files."
3. Save the project inside the Git repository (preferably at the top-level).
4. **Open** the source files from the Git repository.
5. Save the project.

The resulting EPG project file should now have relative paths to the Git repo's SAS programs.

**Questions:**

- [x] Does the relative path stuff work? (i.e., if the project is set up this way, can someone else open up the project and run code?)
    - YES! Tested with Eric and Leslie today in our tech meeting. It works like a charm, very exciting.
- [x] Does this embed data that's produced by the code?
    - That isn't desired; would make projects huge, and would pose issues for security.
    - See my detailed reply with screenshots below.

### PR DESCRIPTION
**Pull request by mooreaw-boisestate**
See #4 for details. I've been going back and forth on how to handle SAS EPG files, and whether or not they should be version-controlled *inside* the Git repository itself. Being able to do this would be smoother, and ensure we have sort of the same "view" of the project each time we open it up, but I need to test this with someone else. Additionally, I want to verify that only the SAS source files are being picked up, and not the output data.

### CODE REVIEW

**Comment by mooreaw-boisestate** [comment]
@ericmwhite-boisestate @lrodom-boisestate Notice how both of you are participants to this conversation-- you've both pushed commits that are on this branch, which are then organized under this PR. (However, you can add a participant to the conversation by `@`'ing them.)

I'm going to do one more check on the EPG project that's in this repository, and then merge the results into `main`. The thing I want to find out is whether the project is embedding the data by default. That would be undesired behavior for our usecase.

**Comment by mooreaw-boisestate** [comment]
Also, I would recommend looking at #4 when you have time, just to see the process for how to set up an EPG project for use with Git/GitHub.

**Comment by lrodom-boisestate** [comment]
So... I just want to try out this comment feature.  Is this a general comment that will be added?  It's not necessarily going to be added to any prior comment thread?
I ask because I see a "Merge pull request" option that says (also wanted to see if a screengrab would work in the Comments section):

image

**Comment by mooreaw-boisestate** [comment]
Yep, this comment gets added to the timeline/stream of replies in *this* pull request. So, it's connected to existing dialogue, if that answers your question? And yes, screengrabs are easy in replies (which is very handy).

**Comment by lrodom-boisestate** [comment]
> @ericmwhite-boisestate @lrodom-boisestate Notice how both of you are participants to this conversation-- you've both pushed commits that are on this branch, which are then organized under this PR. (However, you can add a participant to the conversation by `@`'ing them.)
> 
> I'm going to do one more check on the EPG project that's in this repository, and then merge the results into `main`. The thing I want to find out is whether the project is embedding the data by default. That would be undesired behavior for our usecase.

@ericmwhite-boisestate @mooreaw-boisestate Versus... A comment added where you "quote" the prior comment.  I think I'm getting the hang of the conversation navigation!

**Comment by mooreaw-boisestate** [comment]
Okay, I preserved some screenshots with our `example-data.epg` file that's in this branch on the issue page. Answer seems to be that data files aren't stored in the EPG project file by default, but when HTML results are generated, that does get stored in the EPG project. We should talk over best practices on how to manage this, i.e. how to make sure we don't unintentionally include data files in a Git repo, but I think we can merge things now.

**Comment by mooreaw-boisestate** [comment]
Again, notice how issue #4 was automatically closed upon merge. :)

**Comment by lrodom-boisestate** [comment]
> Yep, this comment gets added to the timeline/stream of replies in _this_ pull request. So, it's connected to existing dialogue, if that answers your question? And yes, screengrabs are easy in replies (which is very handy).

@mooreaw-boisestate Yes, I think I'm understanding this flow.

**Comment by lrodom-boisestate** [comment]
> Again, notice how issue #4 was automatically closed upon merge. :)

You can see all closed issues here, right?
image

**Comment by mooreaw-boisestate** [comment]
Yep! By default, *Open* issues are prioritized, but you can search and view closed issues. You can also interact with them, adding comments, or linking them to projects, etc. You can even *re-open* them, if deemed necessary.

Edit: you can also do the same to Pull Requests that have been merged, as you can see. :)

**Comment by lrodom-boisestate** [comment]
Ah-ha!  I'm liking this!  Mostly because I'm understanding it!

**Pull request merged**
