### PR TITLE
Update example-program.sas

### LINKED ISSUE #2: Hard-coded filepaths aren't ideal for this repository
I'd like to make things smoother for us when working with the code & data in this repository. Currently, in the `source/example-program.sas` file, we have a `PROC IMPORT` statement set up like this:

```sas
PROC IMPORT datafile = 'C:/Users/andrewmoore1/Desktop/example-data/data/midwest.csv'
            dbms = csv
            out = midwest
            replace;
     delimiter = ',';
RUN;
```

This is fine, but anyone wanting to build on the code would need to adjust the argument to `datafile` each time. To prevent this, we can get SAS to read the file directly from the web. It's already loaded/stored on GitHub.com. You can create a reference to it using a `filename` handle, e.g.:

```sas
filename mwdata url 'https://raw.githubusercontent.com/mooreaw-boisestate/example-data/main/data/midwest.csv';
```

The result will mean that a user will (re-)download the data file each time they run the code, but it's not a huge file, and should make things easier.

**To-do:**

- [x] add a filename handle with the link to the raw data in the remote repository
- [x] adjust the `PROC IMPORT` step as needed to ensure the code runs (note that import might need to start on the 3rd line of the file)

### PR DESCRIPTION
**Pull request by mooreaw-boisestate**
This is a pull request to adopt a solution outlined in #2. All changes have been made, but would like feedback from others, and maybe a test to make sure that it works for someone besides me.

### CODE REVIEW

**Review by ericmwhite-boisestate — APPROVED** [review]
This change makes sense to me. I take it that raw.githubusercontent.com/filepath is used to make a public GitHub directory into a source file? Or do You have to copy a file over if you want it to be available?

Edit: I just found your note above and read it.

**Comment by ericmwhite-boisestate** [comment]
I don't know the etiquette for merging pull requests. If I am asked to approve the changes, should I go ahead and merge if I approve? Or is polite to approve and let the original requestor merge the pull request?

**Comment by mooreaw-boisestate** [comment]
I think this practice would be something we'd discuss as an office. Oftentimes, it's likely that it can be informal-- if I'm working together with you, and I request a review, this is just a way to 1) alert you and 2) log that a review happened. As far as merging things in, you might just be able to say "thumbs up! I'll merge this thanks!" or maybe based on the review, you might have feedback like "this all looks good, but make sure you fix ____ based on our meeting earlier today. After you do that, feel free to merge."

Edit: any chance you changed onto the development branch, and tested the new code? :)

**Comment by ericmwhite-boisestate** [comment]
I hadn't thought about doing that. I just switched branches in my desktop client, reopened my local project, confirmed that the file path was changed to the URL, and ran the code. There were no issues.

**Comment by mooreaw-boisestate** [comment]
Perfect, I figured it would work outside my machine, but wanted to make sure. This is where I would merge the changes into our `main` branch-- making them the most up-to-date state of the repository for everyone else. After merging, you usually close the PR, but I'll leave things open for discussion tomorrow.

Edit: oops! Been a while since I've merged a PR-- merging *does* close the request, but I'll be sure to bring things up tomorrow.

**Comment by ericmwhite-boisestate** [comment]
Great, I now see the changes in the main branch!

**Comment by mooreaw-boisestate** [comment]
Note how Issue #2 was automatically closed as a result.

**Comment by ericmwhite-boisestate** [comment]
now that the request is merged, I noticed that I still have the "remove-hardcoded-paths" branch on my GitHub desktop. It is no longer a branch of this project using the web and now the desktop client gives me the option to publish the branch rather than refresh it. Do you normally have to manually delete a branch from your Github desktop whenever you are done working on it?

**Comment by mooreaw-boisestate** [comment]
Yes, what you're describing is normal. This is a consequence of the local/remote dichotomy, and there's a few things to consider. We'll take a big picture view as if this was a "real" project (some of this might be a little redundant or match your current understanding, so bear with me):

1. I make changes locally on a branch titled `remove-hardcoded-paths`, and *push* the local changes up to the remote (GitHub). GitHub now tracks that branch, and it can be pushed to, or pulled down by anyone who's collaborating. If there were more branches that the *remote* is aware of, you'd be able to see them on the remote's page. Here's one place where you can look on the repository's home page.
image

2. As I mentioned, you were able to *pull* everything down, change to the branch locally, and run the code under development. Your local repository now has the development branch preserved at its most recent commit.

3. I merge the changes into our `main` branch, and delete the development branch `remove-hardcoded-paths`. In most cases, once a branch associated with a pull-request has been merged, you should clean up ("trim") un-needed branches, which I'm noted as doing in our conversation thread above.

4. As you've found, my changing something on the remote doesn't immediately affect your local repo. The main reason for this is that in theory, you might have continued developing something relevant on that branch. Perhaps I hit the merge button too-quickly, but you still had more to add. In those instances, you can revive the branch by pushing it again to the remote (you'd be able to open a brand new PR at a later point as well). In this case however, we're all done on the work, so deleting it locally would be the right thing to do.

**Comment by mooreaw-boisestate** [comment]
This is one of the ways that the remote (GitHub) remains the source of truth for code on a project. You can do all the development work you want locally, but at the end of the day, collaborators *pull* down what's most fresh on the remote.

**Pull request merged**
